### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by imshentastic** [imshentastic/Everquote#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by kkossally** [comment]
### Error Handling
- [ ]  errors should not persist once the form has been closed
- [ ] the original site renders errors beneath the inputs, not as a pop-up
- [ ] the signup/login form seems to allow me to login even when the email is not formatted correctly

### Styling
You're styling is quite good!
- [ ] the header on your splash page could more closely mirror the original site
